CREATE DATABASE IF NOT EXISTS batin_pharmacy;

USE batin_pharmacy;

CREATE TABLE IF NOT EXISTS occupation(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	position VARCHAR(255),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS staff(
	id INT NOT NULL AUTO_INCREMENT 	PRIMARY KEY,
	username VARCHAR(255),
	image TEXT,
	gender ENUM ('P','L'),
	email VARCHAR(255),
	password TEXT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	occupation_id INT,
	CONSTRAINT fk_occ FOREIGN KEY (occupation_id) REFERENCES occupation(id),
	CONSTRAINT cs_username UNIQUE (username)
);


CREATE TABLE IF NOT EXISTS history_sales(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username_staff VARCHAR(255),
	category VARCHAR(255),
	does VARCHAR(255),
	quantity INT,
	price INT,
	amount INT,
	date DATETIME,
	CONSTRAINT cs_staff FOREIGN KEY (username_staff) REFERENCES staff(username)
);

CREATE TABLE IF NOT EXISTS category_drugs(
	id INT NOT NULL AUTO_INCREMENT 	PRIMARY KEY,
	category VARCHAR(255),
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS drugs(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255),
	exp_date DATE,
	price INT,
	stock INT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	category_id INT,
	CONSTRAINT cs_catergory FOREIGN KEY(category_id) REFERENCES category_drugs(id)
);

CREATE TABLE IF NOT EXISTS history_sales_drugs(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	id_history_sale INT,
	id_drugs INT,
	CONSTRAINT fk_history_sale FOREIGN KEY(id_history_sale) REFERENCES history_sales(id),
	CONSTRAINT fk_drug FOREIGN KEY(id_drugs) REFERENCES drugs(id)
);

